config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import IndexView, BreedListView, DogListView, DogCreateView, DogUpdateView, DogDeleteView, \
    DogDetailView
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='popular_list'),
    path('breeds/', BreedListView.as_view(), name='breeds'),
    path('<int:pk>/dogs/', DogListView.as_view(), name='breed_dogs'),
    path('view/<int:pk>/', DogDetailView.as_view(), name='view_dog'),
    path('dogs/create', DogCreateView.as_view(), name='dog_create'),
    path('dogs/update/<int:pk>/', DogUpdateView.as_view(), name='dog_update'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, LoginView, LogoutView

path('profile/genpassword', generate_new_password, name='generate_new_password')
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password')
]

mainapp/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'null': True, 'blank': True}


class Breed(models.Model):
    name = models.CharField(max_length=50, verbose_name='название')
    description = models.TextField(max_length=255, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'
        ordering = ('name',)


class Dog(models.Model):
    nickname = models.CharField(max_length=50, verbose_name='кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, **NULLABLE)
    photo = models.ImageField(upload_to='photos/', verbose_name='фотография', **NULLABLE)
    birth_date = models.DateField(verbose_name='дата рождения', **NULLABLE)
    email = models.CharField(max_length=150, unique=True, verbose_name='почта', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.SET_NULL,
                              verbose_name='владелец',
                              **NULLABLE)

    def __str__(self):
        return f'{self.nickname} {self.breed} {self.birth_date}'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'
        ordering = ('nickname',)


class Food(models.Model):
    title = models.CharField(max_length=255, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, verbose_name='собака')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'корм'
        verbose_name_plural = 'корма'


class Parent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, verbose_name='собака')
    nickname = models.CharField(max_length=150, verbose_name='кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='порода')
    birth_date = models.DateField(verbose_name='дата рождения', **NULLABLE)

mainapp/forms.py
import datetime

from django import forms
from django.utils import timezone

from mainapp.models import Dog, Food


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        # fields = '__all__'
        fields = ('nickname', 'breed', 'birth_date', 'photo',)
        # exclude = ('birth_date',)

    def clean_birth_date(self):
        birth_date = self.cleaned_data['birth_date']
        current_date = timezone.now().date()
        years_ago_date = current_date - timezone.timedelta(days=36525)

        if birth_date < years_ago_date or birth_date > current_date:
            raise forms.ValidationError(f'Дата рождения не быть позже текущей даты и ниже на 100 лет')

        return birth_date


class FoodForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Food
        fields = '__all__'


class ParentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Food
        fields = '__all__'

mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from mainapp.forms import DogForm, FoodForm, ParentForm
from mainapp.models import Breed, Dog, Food, Parent
from mainapp.services import get_cached_foods_for_dogs


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'mainapp/index.html'
    extra_context = {
        'title': 'Популярные породы'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Breed.objects.all()[:3]
        return context_data


class BreedListView(LoginRequiredMixin, ListView):
    model = Breed
    extra_context = {
        'title': 'Все породы'
    }


class BreedDetailView(LoginRequiredMixin, DetailView):
    model = Breed


class DogListView(LoginRequiredMixin, ListView):
    model = Dog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(breed_id=self.kwargs.get('pk'))

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        breed_item = Breed.objects.get(pk=self.kwargs.get('pk'))
        context_data['breed_pk'] = breed_item.pk
        context_data['title'] = f'Собаки породы - {breed_item.name}'

        return context_data


class DogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Dog
    form_class = DogForm
    permission_required = 'mainapp.add_dog'
    success_url = reverse_lazy('mainapp:breeds')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class DogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Dog
    permission_required = 'mainapp.change_dog'
    form_class = DogForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('mainapp:breed_dogs', args=[self.object.breed.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        food_formset = inlineformset_factory(Dog, Food, form=FoodForm, extra=1)
        parent_formset = inlineformset_factory(Dog, Parent, form=ParentForm, extra=1)

        if self.request.method == 'POST':
            context_data['food_formset'] = food_formset(self.request.POST, instance=self.object)
            context_data['parent_formset'] = parent_formset(self.request.POST, instance=self.object)
        else:
            context_data['food_formset'] = food_formset(instance=self.object)
            context_data['parent_formset'] = parent_formset(instance=self.object)

        return context_data

    def form_valid(self, form):
        food_formset = self.get_context_data()['food_formset']
        parent_formset = self.get_context_data()['parent_formset']
        self.object = form.save()

        if food_formset.is_valid() and parent_formset.is_valid():
            food_formset.instance = self.object
            parent_formset.instance = self.object

            food_formset.save()
            parent_formset.save()

        return super().form_valid(form)


class DogDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Dog
    permission_required = 'mainapp.view_dog'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['foods'] = get_cached_foods_for_dogs(self.object.pk)
        return context_data


class DogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Dog
    permission_required = 'mainapp.delete_dog'
    success_url = reverse_lazy('mainapp:breeds')

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>
    <header>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container">
            <ul class="list-unstyled d-flex">
                {% if user.is_authenticated %}
                    <li><a class="btn btn-outline-warning" href={% url 'users:profile' %}>Профиль</a></li>
                    <li><a class="btn btn-outline-warning" href={% url 'users:logout' %}>Выйти</a></li>
                {% else %}
                    <li><a class="btn btn-outline-warning" href={% url 'users:register' %}>Регистрация</a></li>
                    <li><a class="btn btn-outline-warning" href={% url 'users:login' %}>Войти</a></li>
                {% endif %}
                <li><a class="btn btn-outline-warning" href={% url 'mainapp:breeds' %}>Породы</a></li>
            </ul>
        </div>
      </div>
    </header>

    <main role="main">
        <div class="container">
            <div class="row">
                <div class="text-uppercase mt-4">
                    <h1>{{ title }}</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            {% block content%}
            {% endblock %}
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/breed_list.html
{% extends 'mainapp/base.html' %}
{% block content %}

<div class="row">
    <div class="col-12 mb-2">
        {% if perms.dogs.add_dog %}
        <a class="btn btn-primary" href={% url 'mainapp:dog_create' %}>Добавить пса</a>
        {% endif %}
    </div>
    {% for object in object_list %}
        {% include 'mainapp/includes/inc_breed.html' %}
    {% endfor %}
</div>

{% endblock %}

mainapp/templates/mainapp/dog_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="card">
            <div class="card_header">
                Удаление собаки
            </div>
            <div class="card_body">
              {% csrf_token %}
              <p>Действительно хотите удалить собаку {{ object.nickname }}</p>
              <button type="submit" class="btn btn-danger">Удалить</button>
              <a class="btn btn-outline-warning" href={% url 'mainapp:breed_dogs' object.breed.pk %}>
                  Отмена
              </a>
            </div>
        </div>
    </form>
{% endblock %}

mainapp/templates/mainapp/dog_detail.html
{% extends 'mainapp/base.html' %}

{% block content %}
        <div class="row">
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        Информация о собаке
                    </div>
                    <div class="card-body">
                      <table class="table">
                          <tr>
                              <td>Кличка</td>
                              <td>{{ object.nickname }}</td>
                          </tr>
                          <tr>
                              <td>Порода</td>
                              <td>{{ object.breed }}</td>
                          </tr>
                          <tr>
                              <td>Дата рождения</td>
                              <td>{{ object.birth_date }}</td>
                          </tr>
                          <tr>
                              <td>Владелец</td>
                              <td>{{ object.owner }}</td>
                          </tr>
                      </table>
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-header">Корм собаки</div>
                    <ul>
                        {% for food in foods %}
                            <li>{{ food }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
{% endblock %}

mainapp/templates/mainapp/dog_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        Редактирование собаки
                    {% else %}
                        Добавление собаки
                    {% endif %}
                </div>
                <div class="card-body">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">
                      {% if object %}
                          Сохранить
                      {% else %}
                          Добавить
                      {% endif %}
                  </button>
                </div>
            </div>
        </div>

        {% if perms.dogs.change_food %}
        <div class="col-4">
            <div class="card">
                <div class="card-header">Корм собаки</div>
                <div class="card-body">
                    {{ food_formset.management_form }}
                    {% for form in food_formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        {% if perms.dogs.change_parent %}
        <div class="col-4">
            <div class="card">
                <div class="card-header">Родитель</div>
                <div class="card-body">
                    {{ parent_formset.management_form }}
                    {% for form in parent_formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

    </form>
{% endblock %}

mainapp/templates/mainapp/dog_list.html
{% extends 'mainapp/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="{{ object.photo|mymedia }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-title">{{ object.nickname|title }}</p>
                        <p class="text-muted">{{ object.birth_date|default:'-' }}</p>
                        <p class="text-muted">Хозяин: {{ object.owner|default:'Без хозяина' }}</p>
                    </div>
                    <div class="card-footer">
                        {% if perms.mainapp.view_dog %}
                            <a class="btn btn-primary" href={% url 'mainapp:view_dog' object.pk %}>Просмотр</a>
                        {% endif %}
                        {% if perms.mainapp.change_dog %}
                            <a class="btn btn-link" href={% url 'mainapp:dog_update' object.pk %}>Изменить</a>
                        {% endif %}
                        {% if perms.mainapp.delete_dog %}
                            <a class="btn btn-danger float-end" href={% url 'mainapp:dog_delete' object.pk %}>Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
            {% include 'mainapp/includes/inc_breed.html' with object=object%}
        {% endfor %}
    </div>
{% endblock %}