config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, LoginView, LogoutView

path('profile/genpassword', generate_new_password, name='generate_new_password')
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mainapp.models import NULLABLE


class User(AbstractUser):
    username = None

    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    telegram = models.CharField(max_length=50, verbose_name='телеграм', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', **NULLABLE)

    email = models.EmailField(unique=True, verbose_name='почта')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mainapp.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.conf import settings
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class LoginView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('mainapp:breeds')


class LogoutView(LogoutView):
    success_url = reverse_lazy('mainapp:popular_list')


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Поздравляем с регистрацией',
            message='Вы зарегистрировались на нашей платформе. Добро пожаловать!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]

        )
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

@login_required
def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('mainapp:popular_list'))

users/templates/users/login.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="h1 card-header p-4">
                    <h3 class="card-title">Вход</h3>
                </div>
                <div class="card-body p-4">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">
                    Войти
                  </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="h1 card-header p-4">
                    <h3 class="card-title">Регистрация</h3>
                </div>
                <div class="card-body p-4">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">
                    Регистрация
                  </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="h1 card-header p-4">
                    <h3 class="card-title">Профиль</h3>
                </div>
                <div class="card-body p-4">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">
                    Сохранить
                  </button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-warning">
                        Сгенерировать пароль
                    </a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}